package collectiondemos;

import java.io.Serializable;

public class Customer implements Comparable<Customer>,Serializable{
	
	private int customerId;
	private String custname;
	private int billamt;
	private String address;

	public Customer() {

	}

	public Customer(int customerId, String custname, String address, int billamt) {
		super();
		this.customerId = customerId;
		this.custname = custname;
		this.billamt = billamt;
		this.address = address;
	}
//We use this to so that we can convert the info inside the object into string and print it.
	
@Override //Why do we write this line?
	public String toString() {
		return "Customer [customerId=" + customerId + ", custname=" + custname + ", billamt=" + billamt + ", address="
				+ address + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((address == null) ? 0 : address.hashCode());
		result = prime * result + billamt;
		result = prime * result + ((custname == null) ? 0 : custname.hashCode());
		result = prime * result + customerId;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Customer other = (Customer) obj;
		if (address == null) {
			if (other.address != null)
				return false;
		} else if (!address.equals(other.address))
			return false;
		if (billamt != other.billamt)
			return false;
		if (custname == null) {
			if (other.custname != null)
				return false;
		} else if (!custname.equals(other.custname))
			return false;
		if (customerId != other.customerId)
			return false;
		return true;
	}

	public int getCustomerId() {
		return customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public String getCustname() {
		return custname;
	}

	public void setCustname(String custname) {
		this.custname = custname;
	}

	public int getBillamt() {
		return billamt;
	}

	public void setBillamt(int billamt) {
		this.billamt = billamt;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	@Override//generated by solving the error
	public int compareTo(Customer arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public Customer getCustomerAddress() {
		// TODO Auto-generated method stub
		return null;
	}
	
}

	